"""Exchange port — strategy never imports a concrete adapter."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from ..core.types import AccountState, Fill, OrderAck, OrderRequest, SymbolMeta


@runtime_checkable
class IExchange(Protocol):
    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def fetch_meta(self) -> dict[str, SymbolMeta]: ...
    async def fetch_account(self) -> AccountState: ...
    async def place_order(self, req: OrderRequest) -> OrderAck: ...
    async def cancel_order(self, symbol: str, exchange_id: str | int) -> bool: ...
    async def cancel_all(self, symbol: str | None = None) -> int: ...
    async def fetch_recent_fills(self, since_ms: int) -> list[Fill]: ...
